const ACTION_TYPES = {
  FETCH_USER_LIST: "FETCH_USER_LIST",
  UPDATE_SELECTED_USERS: "UPDATE_SELECTED_USERS",
  TOGGLE_ALL_USERS_SELECTION: "TOGGLE_ALL_USERS_SELECTION",
  TOGGLE_SORT: "TOGGLE_SORT",
  UPDATE_PAGE: "UPDATE_PAGE",
  SET_IS_LOADING: "SET_IS_LOADING",
};

export default ACTION_TYPES;
